// Auto-generated by openapi-typescript from GET /openapi/v1.json.
// Regenerate after API changes: bun run gen:api (API must be running on :5204).

export interface paths {
  "/": {
    parameters: { query?: never; header?: never; path?: never; cookie?: never };
    get: {
      parameters: { query?: never; header?: never; path?: never; cookie?: never };
      requestBody?: never;
      responses: {
        200: {
          headers: { [name: string]: unknown };
          content: { "application/json": { name: string; version: string | null } };
        };
      };
    };
    put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
  };
  "/api/auth/me": {
    parameters: { query?: never; header?: never; path?: never; cookie?: never };
    get: {
      parameters: { query?: never; header?: never; path?: never; cookie?: never };
      requestBody?: never;
      responses: { 401: { headers: { [name: string]: unknown }; content?: never } };
    };
    put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
  };
  "/api/sites": {
    parameters: { query?: never; header?: never; path?: never; cookie?: never };
    get: operations["GetSites"];
    put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Site: {
      id: string;
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export interface operations {
  GetSites: {
    parameters: { query?: never; header?: never; path?: never; cookie?: never };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: { "application/json": components["schemas"]["Site"][] };
      };
    };
  };
}
